### ISSUE TITLE
Unable to display initial page

### ISSUE THREAD

**Issue by arisliang** [AlphaCat00/PyBaiduPan#6]
Not able to access the initial page.

Python: 3.9
PyBaiduPan: 0.2.0

> * Running on http://127.0.0.1:25000 (Press CTRL+C to quit)
[2022-04-19 11:15:21,984] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\te\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\Miniconda3\envs\te\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\Miniconda3\envs\te\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\Miniconda3\envs\te\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\user\Miniconda3\envs\te\lib\site-packages\pyBaiduPan\login.py", line 43, in login
    data = dict(request.values.dicts[1])

**Comment by xiuliren** [comment]
I also got errors and the link does not work.
Python 3.9.15
```
BdPan -H 0.0.0.0 -P 8080                                                                                                                                                        
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.                                                                        
 * Running on all addresses (0.0.0.0)                                                                                                                                                         
 * Running on http://127.0.0.1:8080                                                                                                                                                           
 * Running on http://xxxxx:8080                                                                                                                                                          
Press CTRL+C to quit                                                                                                                                                                          
[2023-12-19 11:55:39,758] ERROR in app: Exception on / [GET]                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                            
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app  
    response = self.full_dispatch_request()                                                                                                                                                   
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)                                                                                                                                                        
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request                                                                           
    rv = self.dispatch_request()                                                                                                                                                              
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                                                                  
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/pyBaiduPan/login.py", line 43, in login
    data = dict(request.values.dicts[1])                                                                                                                                                      
IndexError: list index out of range   
127.0.0.1 - - [19/Dec/2023 11:55:39] "GET / HTTP/1.1" 500 -                                                                                                                                   
[2023-12-19 11:55:40,076] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):                                                                                                                                                            
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()                                                                                                                                                   
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)                                                                                                                                                        
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()                                                               
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                                                                  
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/pyBaiduPan/login.py", line 43, in login
    data = dict(request.values.dicts[1])                                                                                                                                                      
IndexError: list index out of range                                                                                                                                                           
127.0.0.1 - - [19/Dec/2023 11:55:40] "GET /favicon.ico HTTP/1.1" 500 -                                                                                                                        
[2023-12-19 11:55:42,778] ERROR in app: Exception on / [GET]
Traceback (most recent call last):                                                                                                                                                            
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()                                                                                                                                                   
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request

```

**Comment by raygorous** [comment]
> I also got errors and the link does not work. Python 3.9.15
> 
> ```
> BdPan -H 0.0.0.0 -P 8080                                                                                                                                                        
> WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.                                                                        
>  * Running on all addresses (0.0.0.0)                                                                                                                                                         
>  * Running on http://127.0.0.1:8080                                                                                                                                                           
>  * Running on http://xxxxx:8080                                                                                                                                                          
> Press CTRL+C to quit                                                                                                                                                                          
> [2023-12-19 11:55:39,758] ERROR in app: Exception on / [GET]                                                                                                                                  
> Traceback (most recent call last):                                                                                                                                                            
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app  
>     response = self.full_dispatch_request()                                                                                                                                                   
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
>     rv = self.handle_user_exception(e)                                                                                                                                                        
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request                                                                           
>     rv = self.dispatch_request()                                                                                                                                                              
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                                                                  
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/pyBaiduPan/login.py", line 43, in login
>     data = dict(request.values.dicts[1])                                                                                                                                                      
> IndexError: list index out of range   
> 127.0.0.1 - - [19/Dec/2023 11:55:39] "GET / HTTP/1.1" 500 -                                                                                                                                   
> [2023-12-19 11:55:40,076] ERROR in app: Exception on /favicon.ico [GET]
> Traceback (most recent call last):                                                                                                                                                            
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
>     response = self.full_dispatch_request()                                                                                                                                                   
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
>     rv = self.handle_user_exception(e)                                                                                                                                                        
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
>     rv = self.dispatch_request()                                                               
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                                                                  
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/pyBaiduPan/login.py", line 43, in login
>     data = dict(request.values.dicts[1])                                                                                                                                                      
> IndexError: list index out of range                                                                                                                                                           
> 127.0.0.1 - - [19/Dec/2023 11:55:40] "GET /favicon.ico HTTP/1.1" 500 -                                                                                                                        
> [2023-12-19 11:55:42,778] ERROR in app: Exception on / [GET]
> Traceback (most recent call last):                                                                                                                                                            
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
>     response = self.full_dispatch_request()                                                                                                                                                   
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/mnt/home/jwu/code/backup/env/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
> ```

have you found the solution to this?
